"""Local word list for the memorable-passphrase mode.

Bundled, lowercase, simple English words. This is NOT the official Diceware list
and we do not claim Diceware-level entropy — entropy is computed honestly from
the actual size of this list (see service.estimate_entropy). Picks are made with
``secrets.choice`` only; no external word API is ever contacted.
"""

# A little over 400 short, common, easy-to-type words. Kept lowercase and free
# of ambiguous look-alikes so passphrases stay readable and memorable.
WORDS = [
    "able", "acid", "acre", "actor", "afraid", "after", "again", "agent", "agree",
    "ahead", "alarm", "album", "alert", "alike", "alive", "allow", "alone", "along",
    "alpha", "amber", "angel", "anger", "angle", "ankle", "apple", "april", "apron",
    "arbor", "arena", "argue", "arise", "armor", "array", "arrow", "asset", "atlas",
    "attic", "audio", "audit", "aunt", "avoid", "awake", "award", "aware", "badge",
    "baker", "banjo", "barge", "basic", "basil", "basin", "batch", "beach", "beard",
    "beast", "begin", "being", "below", "bench", "berry", "birch", "birth", "black",
    "blade", "blame", "blank", "blast", "blaze", "bleak", "blend", "bless", "blink",
    "bloom", "board", "boast", "bonus", "boost", "booth", "boots", "bound", "brain",
    "brake", "brand", "brave", "bread", "break", "breed", "brick", "bride", "brief",
    "bring", "brisk", "broad", "brook", "broom", "brown", "brush", "buddy", "build",
    "bunch", "burst", "cabin", "cable", "cache", "camel", "candy", "canoe", "cargo",
    "carve", "catch", "cause", "cedar", "chain", "chair", "chalk", "champ", "chant",
    "charm", "chart", "chase", "cheap", "check", "cheek", "cheer", "chess", "chest",
    "chief", "child", "chili", "chime", "choir", "chord", "chunk", "cider", "cigar",
    "civic", "civil", "claim", "clamp", "clash", "clasp", "class", "clean", "clear",
    "clerk", "click", "cliff", "climb", "cloak", "clock", "close", "cloth", "cloud",
    "clown", "coach", "coast", "cobra", "cocoa", "comet", "coral", "couch", "cough",
    "could", "count", "court", "cover", "crack", "craft", "crane", "crash", "crate",
    "crave", "crawl", "craze", "cream", "creek", "crest", "crisp", "crook", "cross",
    "crowd", "crown", "crumb", "crush", "crust", "curve", "cycle", "daily", "dairy",
    "dance", "decay", "decor", "delta", "depth", "diary", "dimple", "diner", "ditch",
    "diver", "dodge", "donor", "dough", "dozen", "draft", "drain", "drama", "drank",
    "dream", "dress", "dried", "drift", "drill", "drink", "drive", "drone", "eager",
    "eagle", "early", "earth", "easel", "ebony", "elbow", "elder", "elite", "ember",
    "empty", "enjoy", "enter", "entry", "equal", "error", "essay", "ethic", "event",
    "every", "exact", "exile", "exist", "extra", "fable", "facet", "faint", "fairy",
    "faith", "fancy", "feast", "fence", "ferry", "fever", "fiber", "field", "fiery",
    "fifth", "fight", "final", "finch", "first", "flame", "flash", "fleet", "flesh",
    "float", "flock", "flood", "floor", "flour", "fluid", "flush", "flute", "focus",
    "forge", "forth", "found", "frame", "frank", "fresh", "front", "frost", "fruit",
    "fudge", "funny", "gauge", "ghost", "giant", "glade", "gland", "glare", "glass",
    "gleam", "glide", "globe", "gloom", "glory", "glove", "going", "grace", "grade",
    "grain", "grand", "grant", "grape", "graph", "grasp", "grass", "grave", "great",
    "greed", "green", "greet", "grill", "grind", "groan", "groom", "group", "grove",
    "guard", "guess", "guest", "guide", "habit", "happy", "hardy", "harsh", "haste",
    "hatch", "haven", "heart", "heavy", "hedge", "hefty", "hello", "honey", "honor",
    "horse", "hotel", "house", "hover", "human", "humid", "humor", "hurry", "ideal",
    "image", "index", "inner", "input", "intro", "ivory", "jelly", "jewel", "joint",
    "jolly", "judge", "juice", "jumbo", "knack", "knead", "kneel", "knife", "knock",
    "known", "label", "labor", "lance", "large", "laser", "later", "laugh", "layer",
    "learn", "lease", "leash", "ledge", "lemon", "level", "lever", "light", "lilac",
    "linen", "liver", "llama", "loyal", "lucky", "lunar", "lunch", "lyric", "magic",
    "major", "maker", "mango", "manor", "maple", "march", "marsh", "match", "metal",
    "meter", "midst", "might", "miner", "minor", "mixer", "model", "money", "month",
    "moose", "moral", "motor", "mound", "mount", "mouse", "mouth", "movie", "music",
    "naval", "nerve", "newer", "newly", "niece", "night", "noble", "noise", "north",
    "novel", "nurse", "oasis", "ocean", "offer", "olive", "onion", "opera", "orbit",
    "order", "organ", "otter", "ought", "ounce", "outer", "owner", "paint", "panel",
    "paper", "parka", "party", "patch", "pause", "peace", "peach", "pearl", "pedal",
    "penny", "perch", "phase", "phone", "photo", "piano", "piece", "pilot", "pinch",
    "pitch", "pivot", "place", "plain", "plane", "plant", "plate", "plaza", "plead",
    "plump", "poem", "point", "polar", "porch", "pound", "power", "prank", "press",
    "price", "pride", "prime", "print", "prize", "probe", "proof", "proud", "prune",
    "pulse", "punch", "pupil", "puree", "queen", "quest", "quiet", "quilt", "quote",
    "radar", "radio", "rapid", "ratio", "raven", "reach", "react", "ready", "realm",
    "rebel", "relax", "relay", "remix", "renew", "reply", "ridge", "rifle", "rinse",
    "river", "roast", "robin", "robot", "rocky", "round", "route", "royal", "rugby",
    "ruler", "rumor", "rural", "saint", "salad", "salsa", "sauce", "scale", "scarf",
    "scene", "scent", "scoop", "scope", "score", "scout", "scrap", "scrub", "seven",
    "shade", "shake", "shape", "share", "shark", "sharp", "sheep", "sheet", "shelf",
    "shell", "shine", "shiny", "shire", "shock", "shore", "short", "shout", "shrub",
    "siege", "sight", "silly", "siren", "skate", "skull", "slate", "sleep", "slice",
    "slide", "slope", "small", "smart", "smile", "smoke", "snack", "snail", "snake",
    "sneak", "solar", "solid", "sonic", "sound", "south", "space", "spare", "spark",
    "speak", "spear", "spell", "spend", "spice", "spike", "spine", "spire", "spoke",
    "spoon", "sport", "spray", "squad", "stack", "staff", "stage", "stair", "stake",
    "stamp", "stand", "stark", "start", "state", "steam", "steel", "steep", "steer",
    "stern", "stick", "still", "sting", "stock", "stone", "stool", "store", "storm",
    "story", "stove", "strap", "straw", "swamp", "sweep", "sweet", "swift", "swing",
    "sword", "table", "taken", "tango", "taper", "tease", "tempo", "tenor", "thank",
    "theme", "thick", "thigh", "thing", "think", "third", "thorn", "three", "throw",
    "thumb", "tiger", "tight", "title", "toast", "today", "token", "tonic", "tooth",
    "topic", "torch", "total", "touch", "tough", "tower", "trace", "track", "trade",
    "trail", "train", "trait", "trash", "tread", "treat", "trend", "tribe", "trick",
    "tropic", "truck", "truly", "trunk", "trust", "truth", "tulip", "tutor", "twice",
    "twist", "ultra", "uncle", "under", "union", "unite", "unity", "upper", "urban",
    "usage", "usual", "vague", "valid", "valor", "value", "vapor", "vault", "venue",
    "verse", "video", "villa", "vinyl", "viola", "vital", "vivid", "vocal", "vodka",
    "voice", "voter", "wafer", "wager", "wagon", "waist", "waltz", "watch", "water",
    "weary", "weave", "wedge", "whale", "wharf", "wheat", "wheel", "where", "which",
    "while", "white", "whole", "widen", "width", "wield", "willow", "windy", "witch",
    "woman", "world", "worry", "worth", "would", "wound", "woven", "wrist", "write",
    "wrong", "yacht", "yearn", "yeast", "yield", "young", "youth", "zebra",
]

WORDLIST_SIZE = len(WORDS)
